mdapipkg/unpackaged/objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>Finished__c</fullName>
        <label>Finished</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Batches</relationshipLabel>
        <relationshipName>Batches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Log__c</fullName>
        <label>Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notifiable_Errors__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Notifiable Errors</label>
        <precision>12</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Started__c</fullName>
        <label>Started</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Batch</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Batch Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Batch_Log__c.object
<CustomObject>
    <fields>
        <fullName>Batch__c</fullName>
        <label>Batch</label>
        <referenceTo>Batch__c</referenceTo>
        <relationshipLabel>Batch Logs</relationshipLabel>
        <relationshipName>Batch_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch Log</label>
    <nameField>
        <displayFormat>BL-{000000}</displayFormat>
        <label>Batch Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Finished__c</fullName>
        <label>Finished</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <referenceTo>Job_Type__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Log__c</fullName>
        <label>Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Notifiable_Errors__c</fullName>
        <label>Notifiable Errors</label>
        <summarizedField>Batch__c.Notifiable_Errors__c</summarizedField>
        <summaryForeignKey>Batch__c.Job__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Scheduled_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_Hour__c</fullName>
        <label>Scheduled Hour</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheduled_Minute__c</fullName>
        <label>Scheduled Minute</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Started__c</fullName>
        <label>Started</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Job_Log__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job Logs</relationshipLabel>
        <relationshipName>Job_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <label>Job Log</label>
    <nameField>
        <displayFormat>JL-{000000}</displayFormat>
        <label>Job Log Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Job_Type__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Size__c</fullName>
        <label>Batch Size</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_to_Keep_Jobs__c</fullName>
        <defaultValue>90</defaultValue>
        <label>Days to Keep Jobs</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <label>Parameters</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Job Type</label>
    <nameField>
        <label>Job Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/classes/JobSupport.cls
public class JobSupport  
{
	static list<Job_Log__c> jobLogs = new list<Job_Log__c>{};
	static list<Batch_Log__c> batchLogs = new list<Batch_Log__c>{};

	static Job__c currentJob;
	static Batch__c currentBatch;

//  ***************************************************************

	public static void addJobLog (String message)
	{
		if (currentJob == null) return;

		jobLogs.add (new Job_Log__c (Job__c = currentJob.Id, Message__c = message));
	}

//  ***************************************************************

	public static list<Job_Log__c> getJobLogs ()
	{
		return jobLogs;
	}

//  ***************************************************************

	public static void setCurrentJob (Job__c job)
	{
		currentJob = job;
	} 

//  ***************************************************************

	public static void addBatchLog (String message)
	{
		if (currentBatch == null) return;

		batchLogs.add (new Batch_Log__c (Batch__c = currentBatch.Id, Message__c = message));
	}

//  ***************************************************************

	public static list<Batch_Log__c> getBatchLogs ()
	{
		return batchLogs;
	}

//  ***************************************************************

	public static void setCurrentBatch (Batch__c batch)
	{
		currentBatch = batch;
	} 
	
//  ***************************************************************

	public static void cleanupOldJobs (Job__c job)
	{
		Integer daysToKeepJobs = Integer.valueOf((job.Job_Type__r.Days_to_Keep_Jobs__c == null ? 90 : job.Job_Type__r.Days_to_Keep_Jobs__c)) ;

		Date expiryDate = System.today().addDays(-daysToKeepJobs);

		try
		{
			delete [SELECT Id FROM Job__c 
						WHERE Status__c = 'Finished' 
						AND Job_Type__c = :job.Job_Type__c 
						AND CreatedDate < :expiryDate];
		}
		catch (Exception e) {}
	}

//  ***************************************************************

	public static void multiScheduleJob (String jobType, Integer startHour, Integer every)

	//  this method calls multiScheduleJob with no parameters

	{
		multiScheduleJob (jobType, null, startHour, every);
	}

//  ***************************************************************

	public static void multiScheduleJob (String jobType, String parameters, Integer startHour, Integer every)
	{
		if (every == 0) return;
		if (startHour > 23) return;

		for (Integer i=startHour;i<24;i=i+every)
		{
			System.debug (i);
			scheduleJob (jobType, parameters, i, 0);
		}
	}

//  ***************************************************************

	public static void scheduleJob (String jobType, Integer hour, Integer minute)

	//  this method calls scheduleJob with no parameters

	{	
		scheduleJob (jobType, null, hour, minute);
	}

//  ***************************************************************

	public static void scheduleJob (String jobType, String parameters, Integer hour, Integer minute)
	{	
		Job_Type__c jt = new Job_Type__c ();
		
		try
		{
			jt = [SELECT Id, Name, Batch_Size__c FROM Job_Type__c WHERE Name = :jobType LIMIT 1];
		}
		catch (Exception e)
		{
			jt.Name = jobType;
			jt.Batch_Size__c = 25;
			insert jt;
		}
		
		DateTime dt = DateTime.newInstance (System.now().year(), System.now().month(), System.now().day(), hour, minute, 0);
		
		String jobName = jobType + ' Daily at ' + dt.format('HH:mm');
		String scheduledTime = dt.format('ss mm HH ? * 1-7 ****');

        Schedulable obj = (Schedulable) Type.forName(jobType).newInstance();
        Id asyncApexJobId = system.schedule (jobName, scheduledTime, obj);  

		Job__c j = new Job__c (Job_Type__c = jt.Id, Job_Id__c = asyncApexJobId, 
								Parameters__c = parameters, 
								Status__c = 'Repeat Scheduled',
								Scheduled_Hour__c = hour,
								Scheduled_Minute__c = minute);
		insert j;
	}
	
//  ***************************************************************
	
	public static void submitJob (String jobType)

	//  this method calls submitJob with empty Job parameters

	{
		submitJob (jobType, '');
	}

//  ***************************************************************
	
	public static void submitJob (String jobType, Id scheduledJobId)
	{
		Job__c j = getJobForId (scheduledJobId);

		submitJob (jobType, j.Parameters__c, j);
	}

//  ***************************************************************
	
	public static void submitJob (String jobType, String parameters, Job__c parentJob)
	
	//  this method submits an immediate batch job and creates a Job__c record for the code to use
	//  it will optionally create a Job_Type__c record if one is not found in the database with the supplied name
	//  parameters can be supplied in a JSON String
	//  it is only called from submitJob (String jobType, Id scheduledJobId), which is called by the Scheduler calling the execute method
	//  this allows a scheduled job to be connected to it's parent which controls the schedule
	
	{
		Job_Type__c jt = new Job_Type__c ();
		
		try
		{
			jt = [SELECT Id, Batch_Size__c FROM Job_Type__c WHERE Name = :jobType LIMIT 1];
		}
		catch (Exception e)
		{
			jt.Name = jobType;
			jt.Batch_Size__c = 25; 
			insert jt;
		}
		
        Database.Batchable<SObject> obj = (Database.Batchable<SObject>) Type.forName(jobType).newInstance();
        Id asyncApexJobId = Database.executeBatch (obj, Integer.valueOf(jt.Batch_Size__c));  

		Job__c j = new Job__c (Job_Type__c = jt.Id, 
								Job_Id__c = asyncApexJobId, 
								Parameters__c = parameters, 
								Parent_Job__c = parentJob.Id,
								Status__c = 'Scheduled');
		insert j;
	}

//  ***************************************************************
	
	public static void submitJob (String jobType, String parameters)
	
	//  this method submits an immediate batch job and creates a Job__c record for the code to use
	//  it will optionally create a Job_Type__c record if one is not found in the database with the supplied name
	//  parameters can be supplied in a JSON String
	
	{
		Job_Type__c jt = new Job_Type__c ();
		
		try
		{
			jt = [SELECT Id, Batch_Size__c FROM Job_Type__c WHERE Name = :jobType LIMIT 1];
		}
		catch (Exception e)
		{
			jt.Name = jobType;
			jt.Batch_Size__c = 25; 
			insert jt;
		}
		
        Database.Batchable<SObject> obj = (Database.Batchable<SObject>) Type.forName(jobType).newInstance();
        Id asyncApexJobId = Database.executeBatch (obj, Integer.valueOf(jt.Batch_Size__c));  

		Job__c j = new Job__c (Job_Type__c = jt.Id, Job_Id__c = asyncApexJobId, Parameters__c = parameters, Status__c = 'Scheduled');
		insert j;
	}

//  ***************************************************************
	
	public static Job__c getJobForId (Id jobId)
	{		
		try 
		{
			currentJob = [SELECT Id, Parameters__c, Job_Type__c, Job_Type__r.Disabled__c, Job_Type__r.Parameters__c, 
					Job_Type__r.Days_to_Keep_Jobs__c,
					Status__c, Started__c, Finished__c, Log__c 
					FROM Job__c 
					WHERE Job_Id__c = :jobId 
					LIMIT 1];

			cleanupOldJobs (currentJob);
		}
		catch (Exception e) {}


		System.debug('$$$$$$ in getJobForId ' + currentJob);

		return currentJob;
	}

//  ***************************************************************
	
	public static void addLineToJobLog (Job__c job, String line, Boolean updateStatus)
	{
		if (job.Log__c == null)
		{
			job.Log__c = line + '\n';
		}
		else
		{
			job.Log__c += line + '\n';
		}

		if (updateStatus == true)
		{
			job.Status__c = line;
			if (line == 'Started') job.Started__c = System.now();
			if (line == 'Finished' || line == 'Failed') job.Finished__c = System.now();
		}
	}

//  ***************************************************************
	
	public static void addLineToBatchLog (Batch__c batch, String line, Boolean updateStatus)
	{
		if (batch.Log__c == null)
		{
			batch.Log__c = line + '\n';
		}
		else
		{
			batch.Log__c += line + '\n';
		}
		
		if (updateStatus == true)
		{
			batch.Status__c = line;
			if (line == 'Started') batch.Started__c = System.now();
			if (line == 'Finished' || line == 'Failed') batch.Finished__c = System.now();
		}
	}

//  ***************************************************************
	
	public static void addLineToBatchLog (Batch__c batch, String line, Boolean updateStatus, Boolean notifiableError)
	{
		if (notifiableError) 
		{
			if (batch.Notifiable_Errors__c == null)
			{
				batch.Notifiable_Errors__c = 0;
			}
			batch.Notifiable_Errors__c++;
		}
		addLineToBatchLog (batch, line, updateStatus);
	}
}