mdapipkg/unpackaged/objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Batches</relationshipLabel>
        <relationshipName>Batches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Batch</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Batch Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchTestFramework.cls
global with sharing class BatchTestFramework 
							implements Database.Batchable<SObject>,
										Database.Stateful, 
										Database.AllowsCallouts,
										Schedulable 
{
	Boolean testMode;
	public Job__c job; 

//******************************************************************

	global BatchTestFramework() 
	{
		//  nothing to do
	}

//******************************************************************

	global void execute(SchedulableContext sc)  
	{
		JobSupport.submitJob('BatchTestFramework', 'No Parameters');
	}

//******************************************************************

	global database.querylocator start (Database.BatchableContext bc)  //  comment added 
	{		
        this.job = JobSupport.getJobForId (bc.getJobId());
		JobSupport.addLineToJobLog (this.job, 'Started', true);
        update this.job;
																		
		String query = 'SELECT Id, Name FROM Account LIMIT 100';
							
		Database.Querylocator ql = Database.getqueryLocator(query); 
		
		return ql;   
	}

//******************************************************************

	global void execute (Database.BatchableContext bc, list<Account> accounts) 
	{						 

    	Batch__c batch = new Batch__c (Job__c = this.job.Id);
    	
    	JobSupport.addLineToBatchLog (batch, 'Started', true);
		insert batch;

		for (Account a : accounts)
		{
			JobSupport.addLineToBatchLog (batch, 'Processed Account OK: ' + a.Name, false);
		}

    	JobSupport.addLineToBatchLog (batch, 'Finished', true);
		update batch;
	}

//******************************************************************
	
	global void finish (Database.BatchableContext bc)
	{
		JobSupport.addLineToJobLog (this.job, 'Finished', true);	
        update this.job;        
    }
}