mdapipkg/unpackaged/objects/Batch__c.object
<CustomObject>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Batches</relationshipLabel>
        <relationshipName>Batches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Batch</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Batch Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Job__c.object
<CustomObject>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <referenceTo>Job_Type__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Job Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

mdapipkg/unpackaged/objects/Job_Type__c.object
<CustomObject>
    <label>Job Type</label>
    <nameField>
        <label>Job Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapipkg/unpackaged/classes/JobSupport_Test.cls
@isTest
private class JobSupport_Test  
{
    static testMethod void test () 
    {
        Account a1 = new Account (Name = 'Test Account 1');
        insert a1;

        Job_Type__c jt1 = new Job_Type__c (Name='Test 1');
        insert jt1;

        Job__c j1 = new Job__c (Job_Type__c = jt1.Id);
        insert j1;

        Batch__c b1 = new Batch__c (Job__c = j1.Id);

        JobSupport.scheduleJob('BatchTestFramework', 12, 12);
        JobSupport.submitJob('BatchTestFramework');
        JobSupport.multiScheduleJob('BatchTestFramework', 0, 1);

        JobSupport.setCurrentJob (j1);
        JobSupport.addJobLog('Test');
        JobSupport.getJobLogs();

        JobSupport.setCurrentBatch (b1);
        JobSupport.addBatchLog('Test');
        JobSupport.getBatchLogs();
        JobSupport.cleanupOldJobs(j1);
    }
}